[package]
build = "build.rs"
name = "rspotd-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
rspotd = "0.4.0"
slint = "1.5.1"

[build-dependencies]
slint-build = "1.5.1"

[profile.release]
strip = "debuginfo"